
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    # 连接超时时间（ms)
    timeout: 5000ms
    # 高版本springboot中使用jedis或者lettuce
    jedis:
      pool:
        # 连接池最大连接数（负值表示无限制）
        max-active: 8
        # 连接池最大阻塞等待时间（负值无限制)
        max-wait: 5000ms
        # 最大空闲链接数
        max-idle: 8
        # 最小空闲链接数
        min-idle: 1
  # 应用名称
  application:
    name: cache-server
# 应用服务WEB访问端口
server:
  port: 8081