package io.github.syske.springbootwebservicedemo.client2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2020-04-28T16:48:08.286+08:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://service.ws.sample/", name = "Hello2Service")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Hello2Service {

    @WebMethod(action = "urn:SayHello2")
    @WebResult(name = "sayHello2Return", targetNamespace = "http://service.ws.sample/", partName = "parameters")
    public SayHello2Return sayHello2(
            @WebParam(partName = "parameters", name = "sayHello2Param", targetNamespace = "http://service.ws.sample/")
                    SayHello2Param parameters
    );
}
