
package io.github.syske.springbootwebservicedemo.client2;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2020-04-28T16:48:08.141+08:00
 * Generated source version: 3.3.1
 *
 */
public final class Hello2Service_Hello2ServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.ws.sample/", "Hello2Service");

    private Hello2Service_Hello2ServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = Hello2Service_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        Hello2Service_Service ss = new Hello2Service_Service(wsdlURL, SERVICE_NAME);
        Hello2Service port = ss.getHello2ServiceImplPort();

        {
        System.out.println("Invoking sayHello2...");
        SayHello2Param _sayHello2_parameters = new SayHello2Param();
        _sayHello2_parameters.setMyname("fsfsdfsdf");
        SayHello2Return _sayHello2__return = port.sayHello2(_sayHello2_parameters);
        System.out.println("sayHello2.result=" + _sayHello2__return.getHello2());


        }

        System.exit(0);
    }

}
